server:
  name: "media-storage"
  port: ":8003"
  base_path: "/api/v1"
  test_mode: true
  logging:
    level: "debug"
    format: "text"

jwt:
  access_token:
    secret_key: "supersecretkey"
    token_lifetime: 900

aws:
  region: "eu-central-1"
  access_key_id: "your_access_key_id"
  secret_access_key: "your_secret_access_key"
  bucket_name: "your_bucket_name"

kafka:
  brokers:
    - "re-news-kafka:9092"

swagger:
  enabled: true
  url: "/swagger"
  port: "8080"