/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaCollectionData{}

// MediaCollectionData struct for MediaCollectionData
type MediaCollectionData struct {
	Type string `json:"type"`
	Attributes MediaCollectionDataAttributes `json:"attributes"`
}

type _MediaCollectionData MediaCollectionData

// NewMediaCollectionData instantiates a new MediaCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaCollectionData(type_ string, attributes MediaCollectionDataAttributes) *MediaCollectionData {
	this := MediaCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewMediaCollectionDataWithDefaults instantiates a new MediaCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaCollectionDataWithDefaults() *MediaCollectionData {
	this := MediaCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *MediaCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MediaCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MediaCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *MediaCollectionData) GetAttributes() MediaCollectionDataAttributes {
	if o == nil {
		var ret MediaCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *MediaCollectionData) GetAttributesOk() (*MediaCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *MediaCollectionData) SetAttributes(v MediaCollectionDataAttributes) {
	o.Attributes = v
}

func (o MediaCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *MediaCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaCollectionData := _MediaCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaCollectionData)

	if err != nil {
		return err
	}

	*o = MediaCollectionData(varMediaCollectionData)

	return err
}

type NullableMediaCollectionData struct {
	value *MediaCollectionData
	isSet bool
}

func (v NullableMediaCollectionData) Get() *MediaCollectionData {
	return v.value
}

func (v *NullableMediaCollectionData) Set(val *MediaCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaCollectionData(val *MediaCollectionData) *NullableMediaCollectionData {
	return &NullableMediaCollectionData{value: val, isSet: true}
}

func (v NullableMediaCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


