/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateMediaRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMediaRules{}

// CreateMediaRules struct for CreateMediaRules
type CreateMediaRules struct {
	Data CreateMediaRulesData `json:"data"`
}

type _CreateMediaRules CreateMediaRules

// NewCreateMediaRules instantiates a new CreateMediaRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMediaRules(data CreateMediaRulesData) *CreateMediaRules {
	this := CreateMediaRules{}
	this.Data = data
	return &this
}

// NewCreateMediaRulesWithDefaults instantiates a new CreateMediaRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMediaRulesWithDefaults() *CreateMediaRules {
	this := CreateMediaRules{}
	return &this
}

// GetData returns the Data field value
func (o *CreateMediaRules) GetData() CreateMediaRulesData {
	if o == nil {
		var ret CreateMediaRulesData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateMediaRules) GetDataOk() (*CreateMediaRulesData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateMediaRules) SetData(v CreateMediaRulesData) {
	o.Data = v
}

func (o CreateMediaRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMediaRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateMediaRules) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateMediaRules := _CreateMediaRules{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateMediaRules)

	if err != nil {
		return err
	}

	*o = CreateMediaRules(varCreateMediaRules)

	return err
}

type NullableCreateMediaRules struct {
	value *CreateMediaRules
	isSet bool
}

func (v NullableCreateMediaRules) Get() *CreateMediaRules {
	return v.value
}

func (v *NullableCreateMediaRules) Set(val *CreateMediaRules) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMediaRules) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMediaRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMediaRules(val *CreateMediaRules) *NullableCreateMediaRules {
	return &NullableCreateMediaRules{value: val, isSet: true}
}

func (v NullableCreateMediaRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMediaRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


