/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaRulesAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaRulesAttributes{}

// MediaRulesAttributes struct for MediaRulesAttributes
type MediaRulesAttributes struct {
	// Maximum file size in bytes
	MaxSize int64 `json:"max_size"`
	AllowedExits []string `json:"allowed_exits"`
	// Folder where the media is stored
	Folder string `json:"folder"`
	Roles []string `json:"roles"`
}

type _MediaRulesAttributes MediaRulesAttributes

// NewMediaRulesAttributes instantiates a new MediaRulesAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaRulesAttributes(maxSize int64, allowedExits []string, folder string, roles []string) *MediaRulesAttributes {
	this := MediaRulesAttributes{}
	this.MaxSize = maxSize
	this.AllowedExits = allowedExits
	this.Folder = folder
	this.Roles = roles
	return &this
}

// NewMediaRulesAttributesWithDefaults instantiates a new MediaRulesAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaRulesAttributesWithDefaults() *MediaRulesAttributes {
	this := MediaRulesAttributes{}
	return &this
}

// GetMaxSize returns the MaxSize field value
func (o *MediaRulesAttributes) GetMaxSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxSize
}

// GetMaxSizeOk returns a tuple with the MaxSize field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetMaxSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxSize, true
}

// SetMaxSize sets field value
func (o *MediaRulesAttributes) SetMaxSize(v int64) {
	o.MaxSize = v
}

// GetAllowedExits returns the AllowedExits field value
func (o *MediaRulesAttributes) GetAllowedExits() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedExits
}

// GetAllowedExitsOk returns a tuple with the AllowedExits field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetAllowedExitsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedExits, true
}

// SetAllowedExits sets field value
func (o *MediaRulesAttributes) SetAllowedExits(v []string) {
	o.AllowedExits = v
}

// GetFolder returns the Folder field value
func (o *MediaRulesAttributes) GetFolder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Folder
}

// GetFolderOk returns a tuple with the Folder field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetFolderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Folder, true
}

// SetFolder sets field value
func (o *MediaRulesAttributes) SetFolder(v string) {
	o.Folder = v
}

// GetRoles returns the Roles field value
func (o *MediaRulesAttributes) GetRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetRolesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *MediaRulesAttributes) SetRoles(v []string) {
	o.Roles = v
}

func (o MediaRulesAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaRulesAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["max_size"] = o.MaxSize
	toSerialize["allowed_exits"] = o.AllowedExits
	toSerialize["folder"] = o.Folder
	toSerialize["roles"] = o.Roles
	return toSerialize, nil
}

func (o *MediaRulesAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"max_size",
		"allowed_exits",
		"folder",
		"roles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaRulesAttributes := _MediaRulesAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaRulesAttributes)

	if err != nil {
		return err
	}

	*o = MediaRulesAttributes(varMediaRulesAttributes)

	return err
}

type NullableMediaRulesAttributes struct {
	value *MediaRulesAttributes
	isSet bool
}

func (v NullableMediaRulesAttributes) Get() *MediaRulesAttributes {
	return v.value
}

func (v *NullableMediaRulesAttributes) Set(val *MediaRulesAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaRulesAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaRulesAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaRulesAttributes(val *MediaRulesAttributes) *NullableMediaRulesAttributes {
	return &NullableMediaRulesAttributes{value: val, isSet: true}
}

func (v NullableMediaRulesAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaRulesAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


