/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadMediaDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadMediaDataAttributes{}

// UploadMediaDataAttributes struct for UploadMediaDataAttributes
type UploadMediaDataAttributes struct {
	// media resource
	Resource string `json:"resource"`
	// media resource ID
	ResourceId string `json:"resource_id"`
	// media category
	Category string `json:"category"`
}

type _UploadMediaDataAttributes UploadMediaDataAttributes

// NewUploadMediaDataAttributes instantiates a new UploadMediaDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadMediaDataAttributes(resource string, resourceId string, category string) *UploadMediaDataAttributes {
	this := UploadMediaDataAttributes{}
	this.Resource = resource
	this.ResourceId = resourceId
	this.Category = category
	return &this
}

// NewUploadMediaDataAttributesWithDefaults instantiates a new UploadMediaDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadMediaDataAttributesWithDefaults() *UploadMediaDataAttributes {
	this := UploadMediaDataAttributes{}
	return &this
}

// GetResource returns the Resource field value
func (o *UploadMediaDataAttributes) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *UploadMediaDataAttributes) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *UploadMediaDataAttributes) SetResource(v string) {
	o.Resource = v
}

// GetResourceId returns the ResourceId field value
func (o *UploadMediaDataAttributes) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *UploadMediaDataAttributes) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *UploadMediaDataAttributes) SetResourceId(v string) {
	o.ResourceId = v
}

// GetCategory returns the Category field value
func (o *UploadMediaDataAttributes) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *UploadMediaDataAttributes) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *UploadMediaDataAttributes) SetCategory(v string) {
	o.Category = v
}

func (o UploadMediaDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadMediaDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource"] = o.Resource
	toSerialize["resource_id"] = o.ResourceId
	toSerialize["category"] = o.Category
	return toSerialize, nil
}

func (o *UploadMediaDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource",
		"resource_id",
		"category",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadMediaDataAttributes := _UploadMediaDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadMediaDataAttributes)

	if err != nil {
		return err
	}

	*o = UploadMediaDataAttributes(varUploadMediaDataAttributes)

	return err
}

type NullableUploadMediaDataAttributes struct {
	value *UploadMediaDataAttributes
	isSet bool
}

func (v NullableUploadMediaDataAttributes) Get() *UploadMediaDataAttributes {
	return v.value
}

func (v *NullableUploadMediaDataAttributes) Set(val *UploadMediaDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadMediaDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadMediaDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadMediaDataAttributes(val *UploadMediaDataAttributes) *NullableUploadMediaDataAttributes {
	return &NullableUploadMediaDataAttributes{value: val, isSet: true}
}

func (v NullableUploadMediaDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadMediaDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


