/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MediaRulesAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaRulesAttributes{}

// MediaRulesAttributes struct for MediaRulesAttributes
type MediaRulesAttributes struct {
	ExitSize []ExitSizeInner `json:"exit_size"`
	Roles []string `json:"roles"`
	// Date and time when the media rules were last updated
	UpdatedAt time.Time `json:"updated_at"`
	// Date and time when the media rules were created
	CreatedAt time.Time `json:"created_at"`
}

type _MediaRulesAttributes MediaRulesAttributes

// NewMediaRulesAttributes instantiates a new MediaRulesAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaRulesAttributes(exitSize []ExitSizeInner, roles []string, updatedAt time.Time, createdAt time.Time) *MediaRulesAttributes {
	this := MediaRulesAttributes{}
	this.ExitSize = exitSize
	this.Roles = roles
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewMediaRulesAttributesWithDefaults instantiates a new MediaRulesAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaRulesAttributesWithDefaults() *MediaRulesAttributes {
	this := MediaRulesAttributes{}
	return &this
}

// GetExitSize returns the ExitSize field value
func (o *MediaRulesAttributes) GetExitSize() []ExitSizeInner {
	if o == nil {
		var ret []ExitSizeInner
		return ret
	}

	return o.ExitSize
}

// GetExitSizeOk returns a tuple with the ExitSize field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetExitSizeOk() ([]ExitSizeInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExitSize, true
}

// SetExitSize sets field value
func (o *MediaRulesAttributes) SetExitSize(v []ExitSizeInner) {
	o.ExitSize = v
}

// GetRoles returns the Roles field value
func (o *MediaRulesAttributes) GetRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetRolesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *MediaRulesAttributes) SetRoles(v []string) {
	o.Roles = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *MediaRulesAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *MediaRulesAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *MediaRulesAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MediaRulesAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MediaRulesAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o MediaRulesAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaRulesAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["exit_size"] = o.ExitSize
	toSerialize["roles"] = o.Roles
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *MediaRulesAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"exit_size",
		"roles",
		"updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaRulesAttributes := _MediaRulesAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaRulesAttributes)

	if err != nil {
		return err
	}

	*o = MediaRulesAttributes(varMediaRulesAttributes)

	return err
}

type NullableMediaRulesAttributes struct {
	value *MediaRulesAttributes
	isSet bool
}

func (v NullableMediaRulesAttributes) Get() *MediaRulesAttributes {
	return v.value
}

func (v *NullableMediaRulesAttributes) Set(val *MediaRulesAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaRulesAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaRulesAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaRulesAttributes(val *MediaRulesAttributes) *NullableMediaRulesAttributes {
	return &NullableMediaRulesAttributes{value: val, isSet: true}
}

func (v NullableMediaRulesAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaRulesAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


