/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadMedia type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadMedia{}

// UploadMedia struct for UploadMedia
type UploadMedia struct {
	Data UploadMediaData `json:"data"`
}

type _UploadMedia UploadMedia

// NewUploadMedia instantiates a new UploadMedia object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadMedia(data UploadMediaData) *UploadMedia {
	this := UploadMedia{}
	this.Data = data
	return &this
}

// NewUploadMediaWithDefaults instantiates a new UploadMedia object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadMediaWithDefaults() *UploadMedia {
	this := UploadMedia{}
	return &this
}

// GetData returns the Data field value
func (o *UploadMedia) GetData() UploadMediaData {
	if o == nil {
		var ret UploadMediaData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UploadMedia) GetDataOk() (*UploadMediaData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UploadMedia) SetData(v UploadMediaData) {
	o.Data = v
}

func (o UploadMedia) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadMedia) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UploadMedia) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadMedia := _UploadMedia{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadMedia)

	if err != nil {
		return err
	}

	*o = UploadMedia(varUploadMedia)

	return err
}

type NullableUploadMedia struct {
	value *UploadMedia
	isSet bool
}

func (v NullableUploadMedia) Get() *UploadMedia {
	return v.value
}

func (v *NullableUploadMedia) Set(val *UploadMedia) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadMedia) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadMedia) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadMedia(val *UploadMedia) *NullableUploadMedia {
	return &NullableUploadMedia{value: val, isSet: true}
}

func (v NullableUploadMedia) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadMedia) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


