/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaCollection{}

// MediaCollection struct for MediaCollection
type MediaCollection struct {
	Data MediaCollectionData `json:"data"`
}

type _MediaCollection MediaCollection

// NewMediaCollection instantiates a new MediaCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaCollection(data MediaCollectionData) *MediaCollection {
	this := MediaCollection{}
	this.Data = data
	return &this
}

// NewMediaCollectionWithDefaults instantiates a new MediaCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaCollectionWithDefaults() *MediaCollection {
	this := MediaCollection{}
	return &this
}

// GetData returns the Data field value
func (o *MediaCollection) GetData() MediaCollectionData {
	if o == nil {
		var ret MediaCollectionData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MediaCollection) GetDataOk() (*MediaCollectionData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *MediaCollection) SetData(v MediaCollectionData) {
	o.Data = v
}

func (o MediaCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MediaCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaCollection := _MediaCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaCollection)

	if err != nil {
		return err
	}

	*o = MediaCollection(varMediaCollection)

	return err
}

type NullableMediaCollection struct {
	value *MediaCollection
	isSet bool
}

func (v NullableMediaCollection) Get() *MediaCollection {
	return v.value
}

func (v *NullableMediaCollection) Set(val *MediaCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaCollection(val *MediaCollection) *NullableMediaCollection {
	return &NullableMediaCollection{value: val, isSet: true}
}

func (v NullableMediaCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


