/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaData{}

// MediaData struct for MediaData
type MediaData struct {
	// file name
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes MediaAttributes `json:"attributes"`
}

type _MediaData MediaData

// NewMediaData instantiates a new MediaData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaData(id string, type_ string, attributes MediaAttributes) *MediaData {
	this := MediaData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewMediaDataWithDefaults instantiates a new MediaData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaDataWithDefaults() *MediaData {
	this := MediaData{}
	return &this
}

// GetId returns the Id field value
func (o *MediaData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MediaData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MediaData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *MediaData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MediaData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MediaData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *MediaData) GetAttributes() MediaAttributes {
	if o == nil {
		var ret MediaAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *MediaData) GetAttributesOk() (*MediaAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *MediaData) SetAttributes(v MediaAttributes) {
	o.Attributes = v
}

func (o MediaData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *MediaData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaData := _MediaData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaData)

	if err != nil {
		return err
	}

	*o = MediaData(varMediaData)

	return err
}

type NullableMediaData struct {
	value *MediaData
	isSet bool
}

func (v NullableMediaData) Get() *MediaData {
	return v.value
}

func (v *NullableMediaData) Set(val *MediaData) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaData) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaData(val *MediaData) *NullableMediaData {
	return &NullableMediaData{value: val, isSet: true}
}

func (v NullableMediaData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


