/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateMediaRulesData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMediaRulesData{}

// CreateMediaRulesData struct for CreateMediaRulesData
type CreateMediaRulesData struct {
	// media type
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes CreateMediaRulesDataAttributes `json:"attributes"`
}

type _CreateMediaRulesData CreateMediaRulesData

// NewCreateMediaRulesData instantiates a new CreateMediaRulesData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMediaRulesData(id string, type_ string, attributes CreateMediaRulesDataAttributes) *CreateMediaRulesData {
	this := CreateMediaRulesData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateMediaRulesDataWithDefaults instantiates a new CreateMediaRulesData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMediaRulesDataWithDefaults() *CreateMediaRulesData {
	this := CreateMediaRulesData{}
	return &this
}

// GetId returns the Id field value
func (o *CreateMediaRulesData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateMediaRulesData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateMediaRulesData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CreateMediaRulesData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateMediaRulesData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateMediaRulesData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateMediaRulesData) GetAttributes() CreateMediaRulesDataAttributes {
	if o == nil {
		var ret CreateMediaRulesDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateMediaRulesData) GetAttributesOk() (*CreateMediaRulesDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateMediaRulesData) SetAttributes(v CreateMediaRulesDataAttributes) {
	o.Attributes = v
}

func (o CreateMediaRulesData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMediaRulesData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateMediaRulesData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateMediaRulesData := _CreateMediaRulesData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateMediaRulesData)

	if err != nil {
		return err
	}

	*o = CreateMediaRulesData(varCreateMediaRulesData)

	return err
}

type NullableCreateMediaRulesData struct {
	value *CreateMediaRulesData
	isSet bool
}

func (v NullableCreateMediaRulesData) Get() *CreateMediaRulesData {
	return v.value
}

func (v *NullableCreateMediaRulesData) Set(val *CreateMediaRulesData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMediaRulesData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMediaRulesData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMediaRulesData(val *CreateMediaRulesData) *NullableCreateMediaRulesData {
	return &NullableCreateMediaRulesData{value: val, isSet: true}
}

func (v NullableCreateMediaRulesData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMediaRulesData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


