/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaRules{}

// MediaRules struct for MediaRules
type MediaRules struct {
	Data MediaRulesData `json:"data"`
}

type _MediaRules MediaRules

// NewMediaRules instantiates a new MediaRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaRules(data MediaRulesData) *MediaRules {
	this := MediaRules{}
	this.Data = data
	return &this
}

// NewMediaRulesWithDefaults instantiates a new MediaRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaRulesWithDefaults() *MediaRules {
	this := MediaRules{}
	return &this
}

// GetData returns the Data field value
func (o *MediaRules) GetData() MediaRulesData {
	if o == nil {
		var ret MediaRulesData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MediaRules) GetDataOk() (*MediaRulesData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *MediaRules) SetData(v MediaRulesData) {
	o.Data = v
}

func (o MediaRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MediaRules) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaRules := _MediaRules{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaRules)

	if err != nil {
		return err
	}

	*o = MediaRules(varMediaRules)

	return err
}

type NullableMediaRules struct {
	value *MediaRules
	isSet bool
}

func (v NullableMediaRules) Get() *MediaRules {
	return v.value
}

func (v *NullableMediaRules) Set(val *MediaRules) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaRules) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaRules(val *MediaRules) *NullableMediaRules {
	return &NullableMediaRules{value: val, isSet: true}
}

func (v NullableMediaRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


