/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaCollectionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaCollectionDataAttributes{}

// MediaCollectionDataAttributes struct for MediaCollectionDataAttributes
type MediaCollectionDataAttributes struct {
	Data []MediaData `json:"data"`
}

type _MediaCollectionDataAttributes MediaCollectionDataAttributes

// NewMediaCollectionDataAttributes instantiates a new MediaCollectionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaCollectionDataAttributes(data []MediaData) *MediaCollectionDataAttributes {
	this := MediaCollectionDataAttributes{}
	this.Data = data
	return &this
}

// NewMediaCollectionDataAttributesWithDefaults instantiates a new MediaCollectionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaCollectionDataAttributesWithDefaults() *MediaCollectionDataAttributes {
	this := MediaCollectionDataAttributes{}
	return &this
}

// GetData returns the Data field value
func (o *MediaCollectionDataAttributes) GetData() []MediaData {
	if o == nil {
		var ret []MediaData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MediaCollectionDataAttributes) GetDataOk() ([]MediaData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MediaCollectionDataAttributes) SetData(v []MediaData) {
	o.Data = v
}

func (o MediaCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaCollectionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MediaCollectionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaCollectionDataAttributes := _MediaCollectionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaCollectionDataAttributes)

	if err != nil {
		return err
	}

	*o = MediaCollectionDataAttributes(varMediaCollectionDataAttributes)

	return err
}

type NullableMediaCollectionDataAttributes struct {
	value *MediaCollectionDataAttributes
	isSet bool
}

func (v NullableMediaCollectionDataAttributes) Get() *MediaCollectionDataAttributes {
	return v.value
}

func (v *NullableMediaCollectionDataAttributes) Set(val *MediaCollectionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaCollectionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaCollectionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaCollectionDataAttributes(val *MediaCollectionDataAttributes) *NullableMediaCollectionDataAttributes {
	return &NullableMediaCollectionDataAttributes{value: val, isSet: true}
}

func (v NullableMediaCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaCollectionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


