/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaRulesCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaRulesCollectionData{}

// MediaRulesCollectionData struct for MediaRulesCollectionData
type MediaRulesCollectionData struct {
	Type string `json:"type"`
	Attributes MediaRulesCollectionDataAttributes `json:"attributes"`
}

type _MediaRulesCollectionData MediaRulesCollectionData

// NewMediaRulesCollectionData instantiates a new MediaRulesCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaRulesCollectionData(type_ string, attributes MediaRulesCollectionDataAttributes) *MediaRulesCollectionData {
	this := MediaRulesCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewMediaRulesCollectionDataWithDefaults instantiates a new MediaRulesCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaRulesCollectionDataWithDefaults() *MediaRulesCollectionData {
	this := MediaRulesCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *MediaRulesCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MediaRulesCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MediaRulesCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *MediaRulesCollectionData) GetAttributes() MediaRulesCollectionDataAttributes {
	if o == nil {
		var ret MediaRulesCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *MediaRulesCollectionData) GetAttributesOk() (*MediaRulesCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *MediaRulesCollectionData) SetAttributes(v MediaRulesCollectionDataAttributes) {
	o.Attributes = v
}

func (o MediaRulesCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaRulesCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *MediaRulesCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaRulesCollectionData := _MediaRulesCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaRulesCollectionData)

	if err != nil {
		return err
	}

	*o = MediaRulesCollectionData(varMediaRulesCollectionData)

	return err
}

type NullableMediaRulesCollectionData struct {
	value *MediaRulesCollectionData
	isSet bool
}

func (v NullableMediaRulesCollectionData) Get() *MediaRulesCollectionData {
	return v.value
}

func (v *NullableMediaRulesCollectionData) Set(val *MediaRulesCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaRulesCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaRulesCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaRulesCollectionData(val *MediaRulesCollectionData) *NullableMediaRulesCollectionData {
	return &NullableMediaRulesCollectionData{value: val, isSet: true}
}

func (v NullableMediaRulesCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaRulesCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


