/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the MediaCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaCollection{}

// MediaCollection struct for MediaCollection
type MediaCollection struct {
	Data *MediaCollectionData `json:"data,omitempty"`
}

// NewMediaCollection instantiates a new MediaCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaCollection() *MediaCollection {
	this := MediaCollection{}
	return &this
}

// NewMediaCollectionWithDefaults instantiates a new MediaCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaCollectionWithDefaults() *MediaCollection {
	this := MediaCollection{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MediaCollection) GetData() MediaCollectionData {
	if o == nil || IsNil(o.Data) {
		var ret MediaCollectionData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaCollection) GetDataOk() (*MediaCollectionData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MediaCollection) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given MediaCollectionData and assigns it to the Data field.
func (o *MediaCollection) SetData(v MediaCollectionData) {
	o.Data = &v
}

func (o MediaCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableMediaCollection struct {
	value *MediaCollection
	isSet bool
}

func (v NullableMediaCollection) Get() *MediaCollection {
	return v.value
}

func (v *NullableMediaCollection) Set(val *MediaCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaCollection(val *MediaCollection) *NullableMediaCollection {
	return &NullableMediaCollection{value: val, isSet: true}
}

func (v NullableMediaCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


