/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateMediaRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMediaRules{}

// UpdateMediaRules struct for UpdateMediaRules
type UpdateMediaRules struct {
	Data UpdateMediaRulesData `json:"data"`
}

type _UpdateMediaRules UpdateMediaRules

// NewUpdateMediaRules instantiates a new UpdateMediaRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMediaRules(data UpdateMediaRulesData) *UpdateMediaRules {
	this := UpdateMediaRules{}
	this.Data = data
	return &this
}

// NewUpdateMediaRulesWithDefaults instantiates a new UpdateMediaRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMediaRulesWithDefaults() *UpdateMediaRules {
	this := UpdateMediaRules{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateMediaRules) GetData() UpdateMediaRulesData {
	if o == nil {
		var ret UpdateMediaRulesData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateMediaRules) GetDataOk() (*UpdateMediaRulesData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateMediaRules) SetData(v UpdateMediaRulesData) {
	o.Data = v
}

func (o UpdateMediaRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMediaRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateMediaRules) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMediaRules := _UpdateMediaRules{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMediaRules)

	if err != nil {
		return err
	}

	*o = UpdateMediaRules(varUpdateMediaRules)

	return err
}

type NullableUpdateMediaRules struct {
	value *UpdateMediaRules
	isSet bool
}

func (v NullableUpdateMediaRules) Get() *UpdateMediaRules {
	return v.value
}

func (v *NullableUpdateMediaRules) Set(val *UpdateMediaRules) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMediaRules) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMediaRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMediaRules(val *UpdateMediaRules) *NullableUpdateMediaRules {
	return &NullableUpdateMediaRules{value: val, isSet: true}
}

func (v NullableUpdateMediaRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMediaRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


