/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ErrorsErrorsInnerMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorsErrorsInnerMeta{}

// ErrorsErrorsInnerMeta struct for ErrorsErrorsInnerMeta
type ErrorsErrorsInnerMeta struct {
	// Request ID is a unique identifier for the request, used for debugging and tracing
	RequestId string `json:"request_id"`
	// Timestamp is the time when the error occurred, in ISO 8601 format
	Timestamp time.Time `json:"timestamp"`
}

type _ErrorsErrorsInnerMeta ErrorsErrorsInnerMeta

// NewErrorsErrorsInnerMeta instantiates a new ErrorsErrorsInnerMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorsErrorsInnerMeta(requestId string, timestamp time.Time) *ErrorsErrorsInnerMeta {
	this := ErrorsErrorsInnerMeta{}
	this.RequestId = requestId
	this.Timestamp = timestamp
	return &this
}

// NewErrorsErrorsInnerMetaWithDefaults instantiates a new ErrorsErrorsInnerMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorsErrorsInnerMetaWithDefaults() *ErrorsErrorsInnerMeta {
	this := ErrorsErrorsInnerMeta{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ErrorsErrorsInnerMeta) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ErrorsErrorsInnerMeta) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ErrorsErrorsInnerMeta) SetRequestId(v string) {
	o.RequestId = v
}

// GetTimestamp returns the Timestamp field value
func (o *ErrorsErrorsInnerMeta) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ErrorsErrorsInnerMeta) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ErrorsErrorsInnerMeta) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o ErrorsErrorsInnerMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorsErrorsInnerMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["request_id"] = o.RequestId
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *ErrorsErrorsInnerMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"request_id",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorsErrorsInnerMeta := _ErrorsErrorsInnerMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorsErrorsInnerMeta)

	if err != nil {
		return err
	}

	*o = ErrorsErrorsInnerMeta(varErrorsErrorsInnerMeta)

	return err
}

type NullableErrorsErrorsInnerMeta struct {
	value *ErrorsErrorsInnerMeta
	isSet bool
}

func (v NullableErrorsErrorsInnerMeta) Get() *ErrorsErrorsInnerMeta {
	return v.value
}

func (v *NullableErrorsErrorsInnerMeta) Set(val *ErrorsErrorsInnerMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorsErrorsInnerMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorsErrorsInnerMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorsErrorsInnerMeta(val *ErrorsErrorsInnerMeta) *NullableErrorsErrorsInnerMeta {
	return &NullableErrorsErrorsInnerMeta{value: val, isSet: true}
}

func (v NullableErrorsErrorsInnerMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorsErrorsInnerMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


