/*
Title

Title

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MediaRulesCollectionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaRulesCollectionDataAttributes{}

// MediaRulesCollectionDataAttributes struct for MediaRulesCollectionDataAttributes
type MediaRulesCollectionDataAttributes struct {
	Data []MediaData `json:"data"`
}

type _MediaRulesCollectionDataAttributes MediaRulesCollectionDataAttributes

// NewMediaRulesCollectionDataAttributes instantiates a new MediaRulesCollectionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaRulesCollectionDataAttributes(data []MediaData) *MediaRulesCollectionDataAttributes {
	this := MediaRulesCollectionDataAttributes{}
	this.Data = data
	return &this
}

// NewMediaRulesCollectionDataAttributesWithDefaults instantiates a new MediaRulesCollectionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaRulesCollectionDataAttributesWithDefaults() *MediaRulesCollectionDataAttributes {
	this := MediaRulesCollectionDataAttributes{}
	return &this
}

// GetData returns the Data field value
func (o *MediaRulesCollectionDataAttributes) GetData() []MediaData {
	if o == nil {
		var ret []MediaData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MediaRulesCollectionDataAttributes) GetDataOk() ([]MediaData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MediaRulesCollectionDataAttributes) SetData(v []MediaData) {
	o.Data = v
}

func (o MediaRulesCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaRulesCollectionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MediaRulesCollectionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaRulesCollectionDataAttributes := _MediaRulesCollectionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMediaRulesCollectionDataAttributes)

	if err != nil {
		return err
	}

	*o = MediaRulesCollectionDataAttributes(varMediaRulesCollectionDataAttributes)

	return err
}

type NullableMediaRulesCollectionDataAttributes struct {
	value *MediaRulesCollectionDataAttributes
	isSet bool
}

func (v NullableMediaRulesCollectionDataAttributes) Get() *MediaRulesCollectionDataAttributes {
	return v.value
}

func (v *NullableMediaRulesCollectionDataAttributes) Set(val *MediaRulesCollectionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaRulesCollectionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaRulesCollectionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaRulesCollectionDataAttributes(val *MediaRulesCollectionDataAttributes) *NullableMediaRulesCollectionDataAttributes {
	return &NullableMediaRulesCollectionDataAttributes{value: val, isSet: true}
}

func (v NullableMediaRulesCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaRulesCollectionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


