openapi: 3.1.0
info:
  description: Title
  title: Title
  version: 1.0.0
servers:
- url: /
paths:
  /test:
    post:
      description: Test
      responses:
        "201":
          description: successfully
      tags:
      - Test
components:
  schemas:
    Media:
      properties:
        data:
          $ref: '#/components/schemas/MediaData'
      required:
      - data
    MediaData:
      properties:
        id:
          description: file name
          type: string
        type:
          enum:
          - media
          type: string
        attributes:
          $ref: '#/components/schemas/MediaAttributes'
      required:
      - attributes
      - id
      - type
    MediaAttributes:
      properties:
        format:
          description: file format
          type: string
        extension:
          description: file extension
          type: string
        size:
          description: file size in bytes
          format: int64
          type: integer
        url:
          description: media URL
          format: uri
          type: string
        resource:
          description: media resource
          type: string
        resource_id:
          description: media resource ID
          type: string
        category:
          description: media category
          type: string
        owner_id:
          description: media owner ID
          type: string
        created_at:
          description: media creation date and time
          format: date-time
          type: string
      required:
      - category
      - created_at
      - extension
      - format
      - owner_id
      - resource
      - resource_id
      - size
      - url
    MediaCollection:
      properties:
        data:
          $ref: '#/components/schemas/MediaCollection_data'
      required:
      - data
      - links
    UploadMedia:
      properties:
        data:
          $ref: '#/components/schemas/UploadMedia_data'
      required:
      - data
    MediaRules:
      properties:
        data:
          $ref: '#/components/schemas/MediaRulesData'
      required:
      - data
    MediaRulesData:
      properties:
        id:
          description: media rules id
          type: string
        type:
          enum:
          - media_rules
          type: string
        attributes:
          $ref: '#/components/schemas/MediaRulesAttributes'
      required:
      - attributes
      - id
      - type
    MediaRulesAttributes:
      properties:
        extensions:
          items:
            description: Indicates if the media is exit size
            type: string
          type: array
        max_size:
          description: Maximum size of the media in bytes
          format: int64
          type: integer
        roles:
          items:
            description: Roles associated with the media rules
            type: string
          type: array
        updated_at:
          description: Date and time when the media rules were last updated
          format: date-time
          type: string
        created_at:
          description: Date and time when the media rules were created
          format: date-time
          type: string
      required:
      - created_at
      - extensions
      - max_size
      - roles
      - updated_at
    CreateMediaRules:
      properties:
        data:
          $ref: '#/components/schemas/CreateMediaRules_data'
      required:
      - data
    UpdateMediaRules:
      properties:
        data:
          $ref: '#/components/schemas/UpdateMediaRules_data'
      required:
      - data
    MediaRulesCollection:
      properties:
        data:
          $ref: '#/components/schemas/MediaRulesCollection_data'
      required:
      - data
      - links
    MediaCollection_data_attributes:
      properties:
        data:
          items:
            $ref: '#/components/schemas/MediaRulesData'
          type: array
      required:
      - data
    MediaCollection_data:
      properties:
        type:
          enum:
          - media_rules_collection
          type: string
        attributes:
          $ref: '#/components/schemas/MediaCollection_data_attributes'
      required:
      - attributes
      - type
    UploadMedia_data_attributes:
      properties:
        resource:
          description: media resource
          type: string
        resource_id:
          description: media resource ID
          type: string
        category:
          description: media category
          type: string
        owner_id:
          description: media owner ID
          type: string
      required:
      - category
      - owner_id
      - resource
      - resource_id
    UploadMedia_data:
      properties:
        type:
          enum:
          - upload_media
          type: string
        attributes:
          $ref: '#/components/schemas/UploadMedia_data_attributes'
      required:
      - attributes
      - type
    CreateMediaRules_data_attributes:
      properties:
        extensions:
          items:
            description: Indicates if the media is exit size
            type: string
          type: array
        max_size:
          description: Maximum size of the media in bytes
          format: int64
          type: integer
        roles:
          items:
            description: Roles associated with the media rules
            type: string
          type: array
      required:
      - extensions
      - max_size
      - roles
    CreateMediaRules_data:
      properties:
        id:
          description: Unique identifier for the media rules
          type: string
        type:
          enum:
          - create_media_rules
          type: string
        attributes:
          $ref: '#/components/schemas/CreateMediaRules_data_attributes'
      required:
      - attributes
      - id
      - type
    UpdateMediaRules_data_attributes:
      properties:
        extensions:
          items:
            description: Indicates if the media is exit size
            type: string
          type: array
        max_size:
          description: Maximum size of the media in bytes
          format: int64
          type: integer
        roles:
          items:
            description: Roles associated with the media rules
            type: string
          type: array
    UpdateMediaRules_data:
      properties:
        id:
          description: media rules id
          type: string
        type:
          enum:
          - update_media_rules
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateMediaRules_data_attributes'
      required:
      - attributes
      - id
      - type
    MediaRulesCollection_data_attributes:
      properties:
        data:
          items:
            $ref: '#/components/schemas/MediaData'
          type: array
      required:
      - data
    MediaRulesCollection_data:
      properties:
        type:
          enum:
          - media_collection
          type: string
        attributes:
          $ref: '#/components/schemas/MediaRulesCollection_data_attributes'
      required:
      - attributes
      - type
