openapi: 3.0.0
info:
  description: Title
  title: Title
  version: 1.0.0
servers:
- url: /
paths:
  /chains/media-storage/v1/media:
    post:
      description: Upload media to the server
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UploadMedia'
        required: true
      responses:
        "201":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Media'
          description: Media uploaded successfully
        "400":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: One of the parameters is invalid. Refer to the response body
            for details.
        "401":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: You must provide a valid authorization params.
        "404":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Requested resource does not exist.
        "409":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Forbidden
        "500":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error
      summary: Upload Media
      tags:
      - Media
  /chains/media-storage/v1/media/:
    delete:
      description: Delete media from the server
      parameters:
      - description: The ID of the media to delete
        explode: false
        in: path
        name: media_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Media deleted successfully
        "400":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/400'
        "401":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/401'
        "403":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/409'
        "404":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/404'
        "500":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/500'
      summary: Delete Media
      tags:
      - Media
  /chains/media-storage/v1/media-rules/:
    delete:
      description: Delete media Rules
      responses:
        "204":
          description: Media Rules deleted successfully
        "400":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/400'
          description: Bad Request
        "401":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/401'
          description: Unauthorized
        "403":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/409'
          description: User Not Allowed to delete media rules
        "404":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/404'
          description: Not Found Media Rules
        "500":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/500'
          description: Internal Server Error
      summary: Delete Media Rules
      tags:
      - Media Rules
    get:
      description: Get media Rules
      responses:
        "201":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MediaRules'
          description: Media Rules retrieved successfully
        "400":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/400'
          description: Bad Request
        "404":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/404'
          description: Not Found Media Rules
        "500":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/500'
          description: Internal Server Error
      summary: Get Media Rules
      tags:
      - Media Rules
    patch:
      description: Update media Rules
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateMediaRules'
        required: true
      responses:
        "201":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MediaRules'
          description: Media Rules created successfully
        "400":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/400'
          description: Bad Request
        "401":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/401'
          description: Unauthorized
        "403":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/409'
          description: User Not Allowed to create media rules
        "404":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/404'
          description: Not Found Media Rules
        "500":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/500'
          description: Internal Server Error
      summary: Update Media Rules
      tags:
      - Media Rules
    post:
      description: Create media Rules
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateMediaRules'
        required: true
      responses:
        "201":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MediaRules'
          description: Media Rules created successfully
        "400":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/400'
        "401":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/401'
        "403":
          $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/409'
        "409":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/400'
          description: Media Rules already exists
        "500":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/paths/~1chains~1media-storage~1v1~1media/post/responses/500'
          description: Internal Server Error
      summary: Create Media Rules
      tags:
      - Media Rules
components:
  schemas:
    Media:
      properties:
        data:
          $ref: '#/components/schemas/MediaData'
      required:
      - data
      type: object
    MediaData:
      properties:
        id:
          description: file name
          type: string
        type:
          enum:
          - media
          type: string
        attributes:
          $ref: '#/components/schemas/MediaAttributes'
      required:
      - attributes
      - id
      - type
      type: object
    MediaAttributes:
      properties:
        format:
          description: file format
          type: string
        extension:
          description: file extension
          type: string
        size:
          description: file size in bytes
          format: int64
          type: integer
        url:
          description: media URL
          format: uri
          type: string
        resource:
          description: media resource
          type: string
        resource_id:
          description: media resource ID
          type: string
        category:
          description: media category
          type: string
        owner_id:
          description: media owner ID
          type: string
        created_at:
          description: media creation date and time
          format: date-time
          type: string
      required:
      - category
      - created_at
      - extension
      - format
      - owner_id
      - resource
      - resource_id
      - size
      - url
      type: object
    MediaCollection:
      properties:
        data:
          $ref: '#/components/schemas/MediaCollection_data'
      required:
      - data
      - links
      type: object
    UploadMedia:
      properties:
        data:
          $ref: '#/components/schemas/UploadMedia_data'
      required:
      - data
      type: object
    MediaRules:
      properties:
        data:
          $ref: '#/components/schemas/MediaRulesData'
      required:
      - data
      type: object
    MediaRulesData:
      properties:
        id:
          description: media rules id
          type: string
        type:
          enum:
          - media_rules
          type: string
        attributes:
          $ref: '#/components/schemas/MediaRulesAttributes'
      required:
      - attributes
      - id
      - type
      type: object
    MediaRulesAttributes:
      properties:
        extensions:
          items:
            description: Indicates if the media is exit size
            type: string
          type: array
        max_size:
          description: Maximum size of the media in bytes
          format: int64
          type: integer
        roles:
          items:
            description: Roles associated with the media rules
            type: string
          type: array
        updated_at:
          description: Date and time when the media rules were last updated
          format: date-time
          type: string
        created_at:
          description: Date and time when the media rules were created
          format: date-time
          type: string
      required:
      - created_at
      - extensions
      - max_size
      - roles
      - updated_at
      type: object
    CreateMediaRules:
      properties:
        data:
          $ref: '#/components/schemas/CreateMediaRules_data'
      required:
      - data
      type: object
    UpdateMediaRules:
      properties:
        data:
          $ref: '#/components/schemas/UpdateMediaRules_data'
      required:
      - data
      type: object
    MediaRulesCollection:
      properties:
        data:
          $ref: '#/components/schemas/MediaRulesCollection_data'
      required:
      - data
      - links
      type: object
    Errors:
      description: Standard JSON:API error
      properties:
        errors:
          description: Non empty array of errors occurred during request processing
          items:
            $ref: '#/components/schemas/Errors_errors_inner'
          type: array
      required:
      - errors
      type: object
    MediaCollection_data_attributes:
      properties:
        data:
          items:
            $ref: '#/components/schemas/MediaRulesData'
          type: array
      required:
      - data
      type: object
    MediaCollection_data:
      properties:
        type:
          enum:
          - media_rules_collection
          type: string
        attributes:
          $ref: '#/components/schemas/MediaCollection_data_attributes'
      required:
      - attributes
      - type
      type: object
    UploadMedia_data_attributes:
      properties:
        resource:
          description: media resource
          type: string
        resource_id:
          description: media resource ID
          type: string
        category:
          description: media category
          type: string
        owner_id:
          description: media owner ID
          type: string
      required:
      - category
      - owner_id
      - resource
      - resource_id
      type: object
    UploadMedia_data:
      properties:
        type:
          enum:
          - upload_media
          type: string
        attributes:
          $ref: '#/components/schemas/UploadMedia_data_attributes'
      required:
      - attributes
      - type
      type: object
    CreateMediaRules_data_attributes:
      properties:
        extensions:
          items:
            description: Indicates if the media is exit size
            type: string
          type: array
        max_size:
          description: Maximum size of the media in bytes
          format: int64
          type: integer
        roles:
          items:
            description: Roles associated with the media rules
            type: string
          type: array
      required:
      - extensions
      - max_size
      - roles
      type: object
    CreateMediaRules_data:
      properties:
        id:
          description: Unique identifier for the media rules
          type: string
        type:
          enum:
          - create_media_rules
          type: string
        attributes:
          $ref: '#/components/schemas/CreateMediaRules_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UpdateMediaRules_data_attributes:
      properties:
        extensions:
          items:
            description: Indicates if the media is exit size
            type: string
          type: array
        max_size:
          description: Maximum size of the media in bytes
          format: int64
          type: integer
        roles:
          items:
            description: Roles associated with the media rules
            type: string
          type: array
      type: object
    UpdateMediaRules_data:
      properties:
        id:
          description: media rules id
          type: string
        type:
          enum:
          - update_media_rules
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateMediaRules_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    MediaRulesCollection_data_attributes:
      properties:
        data:
          items:
            $ref: '#/components/schemas/MediaData'
          type: array
      required:
      - data
      type: object
    MediaRulesCollection_data:
      properties:
        type:
          enum:
          - media_collection
          type: string
        attributes:
          $ref: '#/components/schemas/MediaRulesCollection_data_attributes'
      required:
      - attributes
      - type
      type: object
    Errors_errors_inner_meta:
      properties:
        request_id:
          description: "Request ID is a unique identifier for the request, used for\
            \ debugging and tracing"
          example: 1234567890abcdef
          type: string
        timestamp:
          description: "Timestamp is the time when the error occurred, in ISO 8601\
            \ format"
          example: 2023-10-01T12:34:56Z
          format: date-time
          type: string
      required:
      - request_id
      - timestamp
      type: object
    Errors_errors_inner:
      properties:
        status:
          description: Status is the HTTP status code applicable to this problem
          enum:
          - 400
          - 401
          - 403
          - 404
          - 409
          - 500
          example: 400
          type: integer
        title:
          description: "Title is a short, human-readable summary of the problem"
          example: Bad Request
          type: string
        code:
          description: "Code is an application-specific error code, expressed as a\
            \ string"
          example: invalid_request
          type: string
        detail:
          description: Detail is a human-readable explanation specific to this occurrence
            of the problem
          example: Request body was expected
          type: string
        meta:
          $ref: '#/components/schemas/Errors_errors_inner_meta'
      required:
      - code
      - detail
      - meta
      - status
      - title
      type: object
