openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    Media:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/MediaData'
    MediaData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          description: file name
        type:
          type: string
          enum:
            - media
        attributes:
          $ref: '#/components/schemas/MediaAttributes'
    MediaAttributes:
      type: object
      required:
        - format
        - size
        - url
        - created_at
      properties:
        format:
          type: string
          description: file format
        size:
          type: integer
          format: int64
          description: file size in bytes
        url:
          type: string
          format: uri
          description: media URL
        created_at:
          type: string
          format: date-time
          description: media creation date and time
    MediaCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - media_rules_collection
            attributes:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/MediaRulesData'
    UploadMedia:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - upload_media
            attributes:
              type: object
              required:
                - resource_id
                - media_type
              properties:
                resource_id:
                  type: string
                  description: resource id
                media_type:
                  type: string
                  description: content type
    MediaRules:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/MediaRulesData'
    MediaRulesData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          description: media type
        type:
          type: string
          enum:
            - media_rules
        attributes:
          $ref: '#/components/schemas/MediaRulesAttributes'
    MediaRulesAttributes:
      type: object
      required:
        - max_size
        - allowed_exits
        - folder
        - roles
      properties:
        max_size:
          type: integer
          format: int64
          description: Maximum file size in bytes
        allowed_exits:
          type: array
          items:
            type: string
            example:
              - .jpg
              - .png
            description: Allowed exits for the media
        folder:
          type: string
          description: Folder where the media is stored
        roles:
          type: array
          items:
            type: string
            enum:
              - admin
              - user
            description: Roles that can access the media
    CreateMediaRules:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              description: media type
            type:
              type: string
              enum:
                - media_rules_create
            attributes:
              type: object
              required:
                - max_size
                - allowed_exits
                - folder
                - roles
              properties:
                max_size:
                  type: integer
                  format: int64
                  description: Maximum file size in bytes
                allowed_exits:
                  type: array
                  items:
                    type: string
                    example:
                      - .jpg
                      - .png
                    description: Allowed exits for the media
                folder:
                  type: string
                  description: Folder where the media is stored
                roles:
                  type: array
                  items:
                    type: string
                    enum:
                      - admin
                      - user
                    description: Roles that can access the media
    UpdateMediaRules:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              description: media type
            type:
              type: string
              enum:
                - media_rules_update
            attributes:
              type: object
              properties:
                max_size:
                  type: integer
                  format: int64
                  description: Maximum file size in bytes
                allowed_exits:
                  type: array
                  items:
                    type: string
                    example:
                      - .jpg
                      - .png
                    description: Allowed exits for the media
                folder:
                  type: string
                  description: Folder where the media is stored
                roles:
                  type: array
                  items:
                    type: string
                    enum:
                      - admin
                      - user
                    description: Roles that can access the media
    MediaRulesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - media_collection
            attributes:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/MediaData'
