openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    Media:
      $ref: './spec/components/schemas/Media.yaml'
    MediaData:
      $ref: './spec/components/schemas/MediaData.yaml'
    MediaAttributes:
      $ref: './spec/components/schemas/MediaAttributes.yaml'
    MediaCollection:
      $ref: './spec/components/schemas/MediaCollection.yaml'
