openapi: 3.0.0
info:
  title: Title
  description: Title
  version: 1.0.0

paths:
  /chains/media-storage/v1/media:
    $ref: './paths/UploadMedia.yaml'

  /chains/media-storage/v1/media/:
    $ref: './paths/Media.yaml'

  /chains/media-storage/v1/media-rules/:
    $ref: './paths/MediaRules.yaml'

components:
  schemas:
    Media:
      $ref: './spec/components/schemas/Media.yaml'
    MediaData:
      $ref: './spec/components/schemas/MediaData.yaml'
    MediaAttributes:
      $ref: './spec/components/schemas/MediaAttributes.yaml'
    MediaCollection:
      $ref: './spec/components/schemas/MediaCollection.yaml'
    UploadMedia:
      $ref: './spec/components/schemas/UploadMedia.yaml'

    MediaRules:
      $ref: './spec/components/schemas/MediaRules.yaml'
    MediaRulesData:
      $ref: './spec/components/schemas/MediaRulesData.yaml'
    MediaRulesAttributes:
      $ref: './spec/components/schemas/MediaRulesAttributes.yaml'
    CreateMediaRules:
      $ref: './spec/components/schemas/CreateMediaRules.yaml'
    UpdateMediaRules:
      $ref: './spec/components/schemas/UpdateMediaRules.yaml'
    MediaRulesCollection:
      $ref: './spec/components/schemas/MediaRulesCollection.yaml'

    Errors:
      $ref: './spec/components/schemas/Errors.yaml'
