openapi: 3.1.1
info:
  title: Title
  description: Title
  version: 1.0.0

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
  /chains/media-storage/v1/media/:
    $ref: './patch/Media.yaml'
  /chains/media-storage/v1/media-rules/{resource}:
    parameters:
      - name: resource
        in: path
        required: true
        schema:
          type: string
        description: Идентификатор ресурсной записи
    $ref: './patch/MediaRules.yaml'

components:
  schemas:
    MediaCollection:
      $ref: './spec/components/schemas/MediaCollection.yaml'
    Media:
      $ref: './spec/components/schemas/Media.yaml'
    MediaData:
      $ref: './spec/components/schemas/MediaData.yaml'
    MediaAttributes:
      $ref: './spec/components/schemas/MediaAttributes.yaml'
    UploadMedia:
      $ref: './spec/components/schemas/UploadMedia.yaml'

    MediaRules:
      $ref: './spec/components/schemas/MediaRules.yaml'
    MediaRulesData:
      $ref: './spec/components/schemas/MediaRulesData.yaml'
    MediaRulesAttributes:
      $ref: './spec/components/schemas/MediaRulesAttributes.yaml'
    CreateMediaRules:
      $ref: './spec/components/schemas/CreateMediaRules.yaml'
    UpdateMediaRules:
      $ref: './spec/components/schemas/UpdateMediaRules.yaml'
    MediaRulesCollection:
      $ref: './spec/components/schemas/MediaRulesCollection.yaml'

    Errors:
      $ref: './spec/components/schemas/Errors.yaml'

  responses:
    InvalidParameter:
      $ref: './spec/components/responses/invalidParameter.yaml'
    InvalidAuth:
      $ref: './spec/components/responses/invalidAuth.yaml'
    NotFound:
      $ref: './spec/components/responses/notFound.yaml'
    Forbidden:
      $ref: './spec/components/responses/forbidden.yaml'
    InternalError:
      $ref: './spec/components/responses/internalError.yaml'
    Conflict:
      $ref: './spec/components/responses/conflict.yaml'
    TooManyRequests:
      $ref: './spec/components/responses/tooManyRequests.yaml'
    UnsupportedMediaType:
      $ref: './spec/components/responses/unsupportedMediaType.yaml'